#!/usr/bin/env bash
# "displays 4 and then bad luck from China for the 4th loop iteration"
# "displays 9 and then bad luck from Japan for the 9th loop iteration"
# "displays 17 and then bad luck from Italy for the 17th loop iteration"
