#!/usr/bin/env bash
# Script that Indefinitely `writes I am alive!`\ 
# to the file `/tmp/my_process` with 2 secs break every iteration

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
